[global]
  server role = standalone server
  server min protocol = SMB2_10
  server max protocol = SMB3
  server signing = mandatory
  map to guest = Never
  smb encrypt = required
  log level = 1
  log file = /dev/stdout
  disable netbios = yes
  smb ports = 445
[music]
  path = /music
  read only = yes
  valid users = gumbo-test
